# Generated by Django 2.0.4 on 2018-06-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='article',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
