# Generated by Django 2.0.4 on 2018-04-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=80)),
                ('char_ans', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pics',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='charect',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendAPI.Article'),
        ),
    ]
