# Generated by Django 2.0.4 on 2018-04-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0002_auto_20180428_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='rep',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
