# Generated by Django 2.0.4 on 2018-05-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0003_auto_20180429_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='pics',
            field=models.ImageField(blank=True, upload_to='templates/media'),
        ),
    ]
