# Generated by Django 2.0.4 on 2018-05-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0004_auto_20180501_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('компьютеры', 'Компьютеры и ноутбуки'), ('комплектующие', 'Компьютерные комплектующие'), ('телефоны', 'Телефоны и связь'), ('Фото', 'Фото и видео'), ('телевизоры', 'Телевизоры и видео'), ('быт тех', 'Бытовая техника'), ('дом', 'Дом и дача')], max_length=80),
        ),
    ]
