# Generated by Django 2.0.4 on 2018-06-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0004_auto_20180603_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pics',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинки'),
        ),
    ]
