# Generated by Django 2.0.4 on 2018-06-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0005_auto_20180604_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='article',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backendAPI.Article'),
        ),
    ]
