# Generated by Django 2.0.4 on 2018-05-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0005_auto_20180501_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('Компьютеры и ноутбуки', 'Компьютеры и ноутбуки'), ('Компьютерные комплектующие', 'Компьютерные комплектующие'), ('Телефоны и связь', 'Телефоны и связь'), ('Фото и видео', 'Фото и видео'), ('Телевизоры и видео', 'Телевизоры и видео'), ('Бытовая техника', 'Бытовая техника'), ('Дом и дача', 'Дом и дача')], max_length=80),
        ),
    ]
