# Generated by Django 2.0.4 on 2018-07-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0006_auto_20180605_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='camera_200.png', upload_to='templates/media', verbose_name='Фото'),
        ),
    ]
