# Generated by Django 2.0.4 on 2018-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0007_auto_20180713_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='templates/media', verbose_name='Фото'),
        ),
    ]
